### PR TITLE
mobile-sdk-10.1.0

### PR DESCRIPTION
**Pull request by christianrowlands**
I am creating an updated release for the SDK to address this issue: https://github.com/element-hq/element-android/issues/8885

As of version 10, the release name was changed to a unified name (aka mobile instead of android) https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#1000-2024-08-07

Also worthy of note, Jitsi stopped packaging the react-native binaries after version android-sdk-8.6.1. You can see this in https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/com/facebook/react

### CODE REVIEW

**Comment by christianrowlands** [comment]
@bmarty , Let me know if I need to change anything.

**Comment by bmarty** [comment]
Thanks for doing this.

I am trying to build 10.2.0 but I am investigating compilation issue.
It does not block from merging this PR with version 10.1.0.

Can you add a Sign-Off to the PR please, so I can merge it?

**Review by bmarty — APPROVED** [review]

**Comment by christianrowlands** [comment]
Ahh, good call. I forgot to sign off on the PR:

Signed-off-by: Christian Rowlands <craxiomdev [at] gmail.com>

Thank you for taking a look!

**Comment by bmarty** [comment]
Thanks. I have build version 10.2.0 and will try to use it in EA.

**Pull request merged**
